/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 TWIN1.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3d/TWIN1.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.08, -0.019]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_2.geometry} material={materials['mtl2.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_3.geometry} material={materials['mtl3.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_4.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_5.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_6.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_7.geometry} material={materials['mtl7.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_8.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_9.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_10.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_12.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_13.geometry} material={materials['mtl13.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_14.geometry} material={materials['mtl14.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_15.geometry} material={materials['mtl15.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_16.geometry} material={materials['mtl16.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_17.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_18.geometry} material={materials['mtl18.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_19.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_20.geometry} material={materials['mtl20.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_21.geometry} material={materials['mtl21.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_22.geometry} material={materials['mtl22.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_23.geometry} material={materials['mtl23.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_24.geometry} material={materials['mtl24.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_25.geometry} material={materials['mtl25.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_27.geometry} material={materials['mtl27.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_28.geometry} material={materials['mtl28.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_29.geometry} material={materials['mtl29.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_30.geometry} material={materials['mtl30.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_31.geometry} material={materials['mtl31.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_32.geometry} material={materials['mtl32.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_33.geometry} material={materials['mtl33.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_34.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_35.geometry} material={materials['mtl35.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_36.geometry} material={materials['mtl36.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_37.geometry} material={materials['mtl37.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_38.geometry} material={materials['mtl38.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_39.geometry} material={materials['mtl39.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3149_41.geometry} material={materials['mtl4.001']} />
        <lineSegments geometry={nodes.meshes0.geometry} material={materials['mtl1.001']} />
        <mesh geometry={nodes.meshes0_1.geometry} material={materials['mtl1.001']} />
        <lineSegments geometry={nodes.meshes10.geometry} material={materials['mtl11.001']} />
        <mesh geometry={nodes.meshes10_1.geometry} material={materials['mtl11.001']} />
        <points geometry={nodes.meshes25.geometry} material={materials['mtl26.001']} />
        <lineSegments geometry={nodes.meshes25_1.geometry} material={materials['mtl26.001']} />
        <mesh geometry={nodes.meshes25_2.geometry} material={materials['mtl26.001']} />
        <lineSegments geometry={nodes.meshes39.geometry} material={materials['mtl40.001']} />
        <mesh geometry={nodes.meshes39_1.geometry} material={materials['mtl40.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3148_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3148_2.geometry} material={materials['mtl34.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3147_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3147_2.geometry} material={materials['mtl34.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3146_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3146_2.geometry} material={materials['mtl34.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3145_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3145_2.geometry} material={materials['mtl34.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3143_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3143_2.geometry} material={materials['mtl34.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3142_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3142_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3142_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3141_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3141_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3141_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3140_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3140_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3140_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3139_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3139_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3139_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3138_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3138_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3138_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3137_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3137_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3137_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3136_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3136_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3136_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3135_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3135_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3135_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3134_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3134_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3134_3.geometry} material={materials['mtl35.001']} />
      </group>
      <group position={[-0.049, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3132_1.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3132_2.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3132_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3131_1.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3131_2.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3131_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[-0.053, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3122_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3122_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3122_3.geometry} material={materials['mtl25.001']} />
      </group>
      <group position={[-0.061, 0.08, -0.035]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3116_5.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3116_2.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3116_3.geometry} material={materials['mtl30.001']} />
        <lineSegments geometry={nodes.meshes97.geometry} material={materials['mtl11.001']} />
        <mesh geometry={nodes.meshes97_1.geometry} material={materials['mtl11.001']} />
        <lineSegments geometry={nodes.meshes100.geometry} material={materials['mtl40.001']} />
        <mesh geometry={nodes.meshes100_1.geometry} material={materials['mtl40.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3110_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3110_2.geometry} material={materials['mtl34.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3110_3.geometry} material={materials['mtl35.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3110_4.geometry} material={materials['mtl36.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3108_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3108_2.geometry} material={materials['mtl33.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3107_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3107_2.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3107_3.geometry} material={materials['mtl32.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3105_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3105_2.geometry} material={materials['mtl33.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3104_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3104_2.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3104_3.geometry} material={materials['mtl32.001']} />
      </group>
      <group position={[-0.153, 0.08, 0.005]} scale={0.026}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3103_1.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3103_2.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3103_3.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3103_4.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3103_5.geometry} material={materials['mtl31.001']} />
      </group>
      <group position={[-0.163, 0.076, 0.026]} scale={0.027}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3100_1.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3100_2.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3100_3.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3100_4.geometry} material={materials['mtl31.001']} />
      </group>
      <group position={[-0.031, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3099_1.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3099_2.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3099_3.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3099_4.geometry} material={materials['mtl29.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3099_5.geometry} material={materials['mtl30.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3098_1.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3098_2.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3098_3.geometry} material={materials['mtl27.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3098_4.geometry} material={materials['mtl28.001']} />
      </group>
      <group position={[0.201, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3097_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3097_2.geometry} material={materials['mtl10.001']} />
        <points geometry={nodes.meshes144.geometry} material={materials['mtl26.001']} />
        <lineSegments geometry={nodes.meshes144_1.geometry} material={materials['mtl26.001']} />
        <mesh geometry={nodes.meshes144_2.geometry} material={materials['mtl26.001']} />
      </group>
      <group position={[0.201, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3096_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3096_2.geometry} material={materials['mtl10.001']} />
        <points geometry={nodes.meshes147.geometry} material={materials['mtl26.001']} />
        <lineSegments geometry={nodes.meshes147_1.geometry} material={materials['mtl26.001']} />
        <mesh geometry={nodes.meshes147_2.geometry} material={materials['mtl26.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3083_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3083_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3083_3.geometry} material={materials['mtl25.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3082_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3082_2.geometry} material={materials['mtl23.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3082_3.geometry} material={materials['mtl24.001']} />
      </group>
      <group position={[-0.3, 0.081, 0.101]} scale={0.032}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3081_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3081_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3081_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3080_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3080_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3080_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3079_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3079_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3079_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[-0.044, 0.08, -0.226]} scale={[0.025, 0.025, 0.035]}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3078_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3078_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3078_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[-0.205, 0.082, 0.001]} scale={0.029}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3077_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3077_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3077_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3072_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3072_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3072_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3070_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3070_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3070_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3068_1.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3068_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3068_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3064_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3064_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3064_3.geometry} material={materials['mtl20.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3060_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3060_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3060_3.geometry} material={materials['mtl20.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3056_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3056_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3056_3.geometry} material={materials['mtl20.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3052_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3052_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3052_3.geometry} material={materials['mtl20.001']} />
      </group>
      <group position={[-0.075, 0.08, 0.011]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3047_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3047_2.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3047_3.geometry} material={materials['mtl16.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3047_4.geometry} material={materials['mtl6.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3047_5.geometry} material={materials['mtl18.001']} />
      </group>
      <group position={[-0.119, 0.08, 0.005]} scale={0.026}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3046_1.geometry} material={materials['mtl10.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3046_2.geometry} material={materials['mtl11.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3046_3.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3046_4.geometry} material={materials['mtl13.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3046_5.geometry} material={materials['mtl14.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3046_6.geometry} material={materials['mtl15.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3044_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3044_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3044_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0.201, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3043_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3043_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3043_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0.201, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3042_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3042_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3042_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[-0.044, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3041_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3041_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3041_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0.147, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3040_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3040_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3040_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3039_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3039_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3039_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3038_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3038_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3038_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3037_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3037_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3037_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3036_1.geometry} material={materials['mtl8.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3036_2.geometry} material={materials['mtl9.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3036_3.geometry} material={materials['mtl10.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3035_1.geometry} material={materials['mtl7.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3035_2.geometry} material={materials['mtl8.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3006_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3006_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3006_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0.035, 0.08, 0.026]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3005_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3005_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3005_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[-0.117, 0.08, 0.059]} scale={0.027}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3004_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3004_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3004_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0.035, 0.08, 0.026]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3003_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3003_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3003_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0.147, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3002_1.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3002_2.geometry} material={materials['mtl5.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3002_3.geometry} material={materials['mtl6.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3076_1.geometry} material={materials.mtl3} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3076_2.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3076_3.geometry} material={materials['mtl22.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3075_1.geometry} material={materials.mtl3} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3075_2.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3075_3.geometry} material={materials['mtl22.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3074_1.geometry} material={materials.mtl3} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3074_2.geometry} material={materials['mtl4.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3074_3.geometry} material={materials['mtl22.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3007_1.geometry} material={materials['mtl2.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3007_2.geometry} material={materials.mtl3} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3007_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[0, 0.08, -0.019]} scale={0.025}>
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3001_1.geometry} material={materials['mtl2.001']} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3001_2.geometry} material={materials.mtl3} />
        <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3001_3.geometry} material={materials['mtl4.001']} />
      </group>
      <group position={[-0.742, 0.046, -0.165]} scale={[3.96, 0.126, 2.47]}>
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-2.812, 0, -0.182]} scale={[1.895, 0.084, 2.572]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3144.geometry} material={materials['mtl35.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3133.geometry} material={materials['mtl35.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3130.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3129.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3128.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3127.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3126.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3125.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3124.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3123.geometry} material={materials['mtl21.001']} position={[-0.053, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3115.geometry} material={materials['mtl38.001']} position={[-0.035, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3114.geometry} material={materials['mtl38.001']} position={[-0.035, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3113.geometry} material={materials['mtl38.001']} position={[-0.035, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3112.geometry} material={materials['mtl38.001']} position={[-0.035, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3111.geometry} material={materials['mtl37.001']} position={[-0.035, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3109.geometry} material={materials['mtl6.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3106.geometry} material={materials['mtl6.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3101.geometry} material={materials['mtl8.001']} position={[-0.163, 0.076, 0.026]} scale={0.027} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3095.geometry} material={materials['mtl4.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3094.geometry} material={materials['mtl4.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3093.geometry} material={materials['mtl4.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3092.geometry} material={materials['mtl4.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3091.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3090.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3089.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3088.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3087.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3086.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3085.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3084.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3073.geometry} material={materials['mtl8.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3071.geometry} material={materials['mtl8.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3069.geometry} material={materials['mtl8.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3067.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3066.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3065.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3063.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3062.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3061.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3059.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3058.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3057.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3055.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3054.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3053.geometry} material={materials['mtl21.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3051.geometry} material={materials['mtl18.001']} position={[0.075, 0.08, 0.078]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3050.geometry} material={materials['mtl18.001']} position={[0.075, 0.08, 0.078]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3049.geometry} material={materials['mtl18.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3048.geometry} material={materials['mtl18.001']} position={[0.075, 0.08, 0.078]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3034.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3033.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3032.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3031.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3030.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3029.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3028.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3027.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3026.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3025.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3024.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3023.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3022.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3021.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3020.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3019.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3018.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3017.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3016.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3015.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3014.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3013.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3012.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3011.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3010.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3009.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.OBJ_PCB_Twin_Edge_Dev_2_S3008.geometry} material={materials['mtl7.001']} position={[0, 0.08, -0.019]} scale={0.025} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Mat_304} position={[0.335, -0.003, 0.952]} scale={[0.083, 0.174, 0.279]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.003']} position={[-3.383, 0.906, -0.614]} scale={[1.166, 0.814, 1.742]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Mat_304} position={[-3.991, -0.174, -2.112]} scale={[0.067, 0.408, 0.067]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Mat_304} position={[-2.522, -0.174, -2.116]} scale={[0.067, 0.408, 0.067]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Mat_304} position={[-3.669, -0.174, 0.875]} scale={[0.067, 0.408, 0.067]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Mat_304} position={[-3.073, -0.174, 0.918]} scale={[0.067, 0.408, 0.067]} />
    </group>
  )
}

useGLTF.preload('/3d/TWIN1.gltf')
